name: Run UI Automation
run-name: UI Automation
on:
  repository_dispatch:
    types: [my-event]

jobs:
  Run-UI-Automation:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run UI test
        working-directory: ./FrameworkFromScratch
        run: |
          mvn clean test -DisRemote=yes

  Clean-up:
    runs-on: ubuntu-latest
    if: ${{failure()}}
    needs: [ Run-UI-Automation ]
    steps:
      - name: Log failure
        run: echo 'UI automation failed, please check the logs'
     
   
